include:
- ./functions/tests/wipedatabase.py
kind: ArchiveUploadSpec
name: functions-tests-wipedatabase-py-DJkW

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: wipedatabase-c2b2b107-f253-4a1c-8057-f4c5ed328b8d
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-tests-wipedatabase-py-DJkW
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-21T02:31:19Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: wipedatabase
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: shared-data
    namespace: ""
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: wipedatabase-c2b2b107-f253-4a1c-8057-f4c5ed328b8d
      namespace: ""
  requestsPerPod: 1
  resources: {}
