include:
- ./functions/bom_data.zip
kind: ArchiveUploadSpec
name: functions-bom-data-zip-xwoD

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: bom-data
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python-39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-bom-data-zip-xwoD
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-15T15:40:43Z"
