include:
- ./functions/api.zip
kind: ArchiveUploadSpec
name: functions-api-zip-qfjS

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: api
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python-39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-api-zip-qfjS
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-17T13:55:55Z"
