include:
- ./functions/epa.zip
kind: ArchiveUploadSpec
name: functions-epa-zip-OoZz

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: epa
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-epa-zip-OoZz
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-13T17:01:54Z"
