apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-homeless-data
spec:
  createingress: true
  functionref:
    functionweights: null
    name: get-homeless-data
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /get-homeless-data
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /get-homeless-data
